---
deployment:
  tasks:
    - export DEPLOYPATH=/home/margall9/margalla-travels-backend/
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH